import os
import math
import numpy as np

# the max number of heavy atoms of a molecule
# Nanotechnology 26 (2015) 354003,Phys.Chem.Chem.Phys., 2014, 16, 7919
MAX_NUM_HEAVY_ATOMS = 16
# the max number of aromatic rings of a molecule
MAX_NUM_AROMATIC_RING = 1
# the max atomic weight of a molecule
MAX_MOL_WEIGHT = 600.0
# the elements must be included in a molecule
NEEDED_ELEMENTS = ["C"]
# one of the elements should be included in a molecule
OPTIONAL_ELEMENTS = ["O", "N"]
# all elements of a molecule should be included in this list,
# Nanotechnology 26 (2015) 354003,  Phys.Chem.Chem.Phys., 2014, 16, 7919
VALID_ELEMENTS = ["H", "C", "N", "O", "F", "P", "S", "Cl"]

# possible Isotopic elements, https://en.wikipedia.org/wiki/Category:Lists_of_isotopes_by_element
ISOTOPIC_SYMBOL = ["2H", "3H"]
for iso_atomic_num in range(8,23): # C
    if iso_atomic_num != 12:
        ISOTOPIC_SYMBOL.append("%dC"%(iso_atomic_num))
for iso_atomic_num in range(9, 24): #N
    if iso_atomic_num != 14:
        ISOTOPIC_SYMBOL.append("%dN" % (iso_atomic_num))
for iso_atomic_num in range(11, 29): #O
    if iso_atomic_num != 16:
        ISOTOPIC_SYMBOL.append("%dO" % (iso_atomic_num))
for iso_atomic_num in range(13, 32): #F
    if iso_atomic_num != 19:
        ISOTOPIC_SYMBOL.append("%dF" % (iso_atomic_num))
for iso_atomic_num in range(26, 48): #P
    if iso_atomic_num != 31:
        ISOTOPIC_SYMBOL.append("%dP" % (iso_atomic_num))
for iso_atomic_num in range(27, 50): #S
    if iso_atomic_num != 32:
        ISOTOPIC_SYMBOL.append("%dS" % (iso_atomic_num))
for iso_atomic_num in range(28, 53): #Cl
    if iso_atomic_num != 35:
        ISOTOPIC_SYMBOL.append("%dCl" % (iso_atomic_num))

# minimual similarity to known solvents
NUM_BIT_MORGAN = 2048
MIN_SIMILARITY = 0.20

#
def check_no_special_group(smiles):

    # remove smiles includes several different compounds
    if "." in smiles:
        return False

    # remove possible ions (maybe ionic liquid), except for NO2
    if "+" in smiles or "-" in smiles:

        if not ("[N+]" in smiles and "[O-]" in smiles) and not ("[n+]" in smiles and "[O-]" in smiles)\
                and not ("[n+]" in smiles and "[o-]" in smiles):
            return False

    # when setting the ignore_H in GraphInvent is true, explicit H in smiles is not allowed
    # also remove smiles with unusual groups
    if "[PH]" in smiles or "[pH]" in smiles or "[SH]" in smiles or "[sH]" in smiles:
        return False

    return True

# Molecular graphes can't represent the isomers, J Cheminform 12, 56 (2020). https://doi.org/10.1186/s13321-020-00460-5
# Smiles generated by rdkit from mol_with H do not include the isomeric information (isomericSmiles=False)
# So this item is introduced only for collecting the Batt-SLM dataset
def check_no_isomer(smiles):

    if "/" in smiles or "\\" in smiles or "@" in smiles:
        return False

    is_no_isomer = True
    for symbol in ISOTOPIC_SYMBOL:
        temp1 = "[%s" % (symbol)
        temp2 = "%s]" % (symbol)
        if temp1 in smiles or temp2 in smiles:
            is_no_isomer = False
            break

    return is_no_isomer


# check radicals and total charge
def check_no_radical_neutral(rdkit_mol):

    # non-radicals
    from rdkit.Chem import Descriptors
    num_radical = Descriptors.NumRadicalElectrons(rdkit_mol)
    if num_radical > 0:
        return False

    # net charge = 0
    from rdkit.Chem import rdPartialCharges
    rdPartialCharges.ComputeGasteigerCharges(rdkit_mol)
    atomic_charges = [atom.GetDoubleProp('_GasteigerCharge') for atom in rdkit_mol.GetAtoms()]
    tot_charge = math.fabs(sum(atomic_charges))
    if tot_charge > 1E-2:
        return False
    
    # the Normal Charge of H in GraphInVent is usually (-1,0,1)
    from rdkit.Chem import rdqueries
    query = rdqueries.AtomNumEqualsQueryAtom(1)
    mol_atoms = rdkit_mol.GetAtomsMatchingQuery(query)
    hydrogen_formal_charge = [atom.GetFormalCharge() for atom in mol_atoms]
    if len(hydrogen_formal_charge) > 0 and np.max(hydrogen_formal_charge) > 1.0:
        return False

    return True

#
def check_is_solvent_like(rdkit_mol):

    from rdkit import Chem
    from rdkit.Chem import Lipinski

    num_nonH = rdkit_mol.GetNumHeavyAtoms()
    if num_nonH < 3 or num_nonH > MAX_NUM_HEAVY_ATOMS:
        return False

    if Chem.rdMolDescriptors.CalcExactMolWt(rdkit_mol) > MAX_MOL_WEIGHT:
        return False

    is_valid_elem = True
    atom_symbols = [atom.GetSymbol() for atom in rdkit_mol.GetAtoms()]
    for symbol in atom_symbols:
        if symbol not in VALID_ELEMENTS:
            is_valid_elem = False
    if not is_valid_elem:
        return False

    num_aromatic_ring = Lipinski.NumAromaticRings(rdkit_mol)
    if num_aromatic_ring > MAX_NUM_AROMATIC_RING:
        return False

    return True

#
def check_is_suitable_to_battery(rdkit_mol, fingerprints_ref_solvents):

    # at least one C atom, must include O/N atoms
    atom_symbols = [atom.GetSymbol() for atom in rdkit_mol.GetAtoms()]
    is_valid_elem = True
    is_with_need_elem = False
    is_with_optional_elem = False
    for symbol in atom_symbols:
        if symbol not in VALID_ELEMENTS:
            is_valid_elem = False
        elif symbol in NEEDED_ELEMENTS:
            is_with_need_elem = True
        elif symbol in OPTIONAL_ELEMENTS:
            is_with_optional_elem = True
    if not (is_valid_elem and is_with_need_elem and is_with_optional_elem):
        return False

    # check OH, NH, SH
    from rdkit.Chem import rdqueries
    queryO = rdqueries.AtomNumEqualsQueryAtom(8)
    oxygen_rdkit_atoms = rdkit_mol.GetAtomsMatchingQuery(queryO)

    is_aprotic = True
    for atom in oxygen_rdkit_atoms:
        neighbour_rdkit_atoms = atom.GetNeighbors()
        neighbour_rdkit_atoms_symbol = [neighbor.GetSymbol() for neighbor in neighbour_rdkit_atoms]
        if "H" in neighbour_rdkit_atoms_symbol:
            is_aprotic = False
            break

    queryN = rdqueries.AtomNumEqualsQueryAtom(7)
    nitrogen_rdkit_atoms = rdkit_mol.GetAtomsMatchingQuery(queryN)
    for atom in nitrogen_rdkit_atoms:
        neighbour_rdkit_atoms = atom.GetNeighbors()
        neighbour_rdkit_atoms_symbol = [neighbor.GetSymbol() for neighbor in neighbour_rdkit_atoms]
        if "H" in neighbour_rdkit_atoms_symbol:
            is_aprotic = False
            break

    if not is_aprotic:
        return False

    queryS = rdqueries.AtomNumEqualsQueryAtom(16)
    sulfur_rdkit_atoms = rdkit_mol.GetAtomsMatchingQuery(queryS)
    for atom in sulfur_rdkit_atoms:
        neighbour_rdkit_atoms = atom.GetNeighbors()
        neighbour_rdkit_atoms_symbol = [neighbor.GetSymbol() for neighbor in neighbour_rdkit_atoms]
        if "H" in neighbour_rdkit_atoms_symbol:
            is_aprotic = False
            break

    if not is_aprotic:
        return False

    if len(fingerprints_ref_solvents) > 0:
        from rdkit import DataStructs
        from rdkit.Chem import AllChem
        fingerprints = AllChem.GetMorganFingerprintAsBitVect(rdkit_mol, 2, NUM_BIT_MORGAN)
        smilarities = DataStructs.BulkTanimotoSimilarity(fingerprints, fingerprints_ref_solvents)
        max_simi = np.max(smilarities)
        if max_simi < MIN_SIMILARITY:
            return False

    return True

# 
def filter_smiles():

    from pathlib import Path
    from rdkit import Chem
    from rdkit.Chem import AllChem

    input_file_name = "Features"
    WORK_DIR = Path("your_own_path/Batt-SLM")

    smiles = []
    mols_with_hydrogen = []
    with open(WORK_DIR / f"{input_file_name}.csv", "r") as f:
        lines = f.readlines()
        titles = lines[0].strip("\n").split(";")
        smiles_col = titles.index("SMILES")
        smiles = [l.strip("\n").split(";")[smiles_col] for l in lines[1:]]
        mols_with_hydrogen = [Chem.AddHs(Chem.MolFromSmiles(smi)) for smi in smiles]

    # 
    solvent_reference_file = WORK_DIR / "KBS-FP-174.smi"
    print(solvent_reference_file)

    fingerprints_ref_solvents = []
    with open(solvent_reference_file, "r") as f:
        read_lines = f.readlines()
        for line in read_lines:
            cur_mol = Chem.AddHs(Chem.MolFromSmiles(line.split(" ")[0]))
            fingerprints_ref_solvents.append(AllChem.GetMorganFingerprintAsBitVect(cur_mol, 2, NUM_BIT_MORGAN))

    mol_scores = [0.0] * len(smiles)
    for mol_index in range(0, len(smiles)):

        print(mol_index)

        if not check_no_special_group(smiles[mol_index]):
            continue

        if not check_no_isomer(smiles[mol_index]):
            continue

        if not check_no_radical_neutral(mols_with_hydrogen[mol_index]):
            continue

        if not check_is_solvent_like(mols_with_hydrogen[mol_index]):
            continue

        if not check_is_suitable_to_battery(mols_with_hydrogen[mol_index], fingerprints_ref_solvents):
            continue

        mol_scores[mol_index] = 1.0

    # output file, skip the SbCl5 and DCE
    output_file = WORK_DIR / f"{input_file_name}-filters.csv"
    with open(output_file, "w") as g:
        g.write(lines[0].strip("\n") + ";PassFilters\n")
        for index in range(0, len(smiles)):
            g.write(lines[index+1].strip("\n") + ";%d\n"%(mol_scores[index]))

#
if __name__ == "__main__":

    filter_smiles()

